name: hrc110
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pip
  - pip:
      - opencv-python>=4.8
      - numpy>=1.24
      - matplotlib>=3.7
      - pillow>=10.0
      - pytesseract>=0.3.10
      - pyserial>=3.5
      - google-generativeai>=0.8.3
